# Generated by Django 5.2.4 on 2025-07-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanseincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expanseincome',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
